name: 'Tests'

on: ["push"]


jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ vars.TEST_SECRET }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup Go 1.25.x
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'

      - name: Install dependencies
        run: go mod download

      - name: Build service
        run: |
          go build -o ./auth ./cmd/auth
      - name: Set up database
        run: |
          mkdir storage
          go run ./cmd/migrator --storage-path=./storage/test.db --migrations-path=./migrations

      - name: Add admins
        run: |
          go run ./cmd/admins --storage=./storage/test.db --admins=./config/admins.yaml

      - name: Run service
        run: |
          nohup ./auth --config=./config/tests.yaml &

      - name: Run tests
        run: go test -v ./tests
